AWSTemplateFormatVersion: "2010-09-09"

Description: Create S3 Bucket. Get bucket name as a parameter

Parameters:
  BucketNameParam:
    Default: 'lindy-lewis-lab-1-1-5-bucket-default'
    Description: 'Name of the Bucket to be created. Must be globally-unique.'
    Type: String
  PreferredRegion:
    Description: Preferred AWS region
    Type: String
    Default: us-east-1

Conditions:
    IsPreferredRegion: !Equals [!Ref "AWS::Region", !Ref PreferredRegion]

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [IsPreferredRegion, !Join [ "-", [ !Ref AWS::AccountId, !Ref BucketNameParam]], !Join [ "-", [ !Ref AWS::Region, !Ref BucketNameParam]]]
